### ISSUE TITLE
Deutsche Post "Kompakt" is missing

### ISSUE THREAD

**Issue by 4irm** [netresearch/deutschepost-module-internetmarke#1]
Dear Support,

There is a Deutsche Post product missing. "Kompakt Brief" is not available - quite strange since Groß and Maxi is available in the interface. (Available products have been updated)

![image](https://user-images.githubusercontent.com/28482836/129732667-53cdea6a-f8c4-4a70-9d5e-aa7b61d49974.png)

Thanks!

**Comment by mam08ixo** [comment]
The Deutsche Post Internetmarke module allows to purchase vouchers for a subset of all the existing DP shipping products only. Some products (e.g. postcard) are intentionally omitted.

Kompaktbrief (PPL ID 11) is another example.

https://github.com/netresearch/deutschepost-module-internetmarke/blob/1587886d2d4ac7c5bf081015ffde0ddd98910cb8/Model/ProductList/ProductFilter.php#L24-L34

**Comment by ngolatka** [comment]
_internal ref: DHLGW-1040_
